### ISSUE TITLE
bayesopt not working

### ISSUE THREAD

**Issue by pawkonds** [alok-ai-lab/DeepInsight#8]
Hello Sir.
I download your repository and try to run it. When I run it locally, on laptop 'bayesopt' function starts - the graph display - but due to low parameter of the laptop Matlab crashes. I have also access to big cluster, but here is a strange problem - algorithm ends during 'bayesopt'. I even modify the code
```
disp('pre-bayes')

BayesObject = bayesopt(ObjFcn,optimVars,...
    'MaxObj',100,...
    'MaxTime',2*60*60,...
    'IsObjectiveDeterministic',false,...    
    'UseParallel',false);

disp('post-bayes')
```

and in the output file last line is 'pre-bayes'.

I checked and Matlab version on cluster is 2019b with Statistics and Machine Learning Toolbox. 
Additionally, the example bayesopt function from Matlab - https://www.mathworks.com/help/stats/bayesopt.html is working on cluster just fine.

Do you have any ideas what could be a problem?

Sincerely,
Pawel

**Comment by alok-ai-lab** [comment]
Hi Pawel
What is your error?
I think in file makeObjFcn2.m, under trainingOptions the variable 'Execution Environment' is set as 'multi-gpu'. It is possible that your laptop does not support this environment and perhaps that's why crashing.

You may need to set 'Execution Environment' according to your hardware specifications. If your laptop has only CPU then set it as 'cpu' or 'auto'. Please check more details at https://www.mathworks.com/help/deeplearning/ref/trainingoptions.html

Best wishes

**Comment by pawkonds** [comment]
Sir
thank you a lot! 'multi-gpu' was the problem. My laptop is too 'soft' for that algorithm and on cluster I was using CPU query.

Thank you one more time!

Best regards
